FROM node:11-alpine

WORKDIR /workspace

COPY package.json yarn.lock /workspace/

RUN yarn install

COPY . .

ARG NODE_ENV=production
ARG SENDGRID_API_KEY
ARG RECAPTCHA_CLIENT_KEY
ARG RECAPTCHA_SERVER_KEY
ARG GA_TAG

ENV NODE_ENV ${NODE_ENV}
ENV SENDGRID_API_KEY ${SENDGRID_API_KEY}
ENV RECAPTCHA_CLIENT_KEY ${RECAPTCHA_CLIENT_KEY}
ENV RECAPTCHA_SERVER_KEY ${RECAPTCHA_SERVER_KEY}
ENV GA_TAG ${GA_TAG}

RUN yarn build

CMD ["yarn", "start", "-p", "5000"]
